### ISSUE TITLE
wskdebug fails if path argument is missing

### ISSUE THREAD

**Issue by alexkli** [adobe/wskdebug#15]
Apparently #11 wasn't properly fixed or some other change reintroduced it.

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
    at Object.lstatSync (fs.js:834:3)
    at Object.lstatSync (/usr/local/lib/node_modules/@adobe/wskdebug/node_modules/graceful-fs/polyfills.js:308:16)
    at OpenWhiskInvoker.startContainer (/usr/local/lib/node_modules/@adobe/wskdebug/src/invoker.js:123:16)
    at OpenWhiskInvoker.start (/usr/local/lib/node_modules/@adobe/wskdebug/src/invoker.js:78:20)
    at Debugger.run (/usr/local/lib/node_modules/@adobe/wskdebug/src/debugger.js:103:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by alexkli** [comment]
Fixed.
